services:
  backend:
    image: ghcr.io/hasaanhameed/botanique-backend:latest
    container_name: botanique_backend
    ports:
      - "8000:8000"
    env_file:
      - ./botanique_backend/.env
    restart: always

  redis:
    image: redis:alpine
    container_name: botanique_redis
    ports:
      - "6379:6379"
    restart: always
